Repository jenkinsci/docker-inbound-agent, pull requests merged in 2019-09, with the labels that each got.

#108 [JENKINS-42846] - Update the base image to 3.35-2 to fix the broken agent.jar regression
  Dockerfile
Labels: bug

#111 Integrate the JDK11 Image into the master branch
  Dockerfile-jdk11
Labels: chore

#107 Add Gitter and GitHub Releases badges to README
  README.md
Labels: documentation

#112 Integrate the alpine image into the master branch
  Dockerfile-alpine
  README.md
Labels: chore

#114 #103 - Build alpine and jdk11 images during the CI run
  Makefile
Labels: chore

#106 [JENKINS-42846] - Rename the jenkins-slave script to jenkins-agent
  Dockerfile
  Dockerfile-alpine
  Dockerfile-jdk11
  jenkins-agent
  jenkins-agent.ps1
Labels: enhancement

#115 Add the executable flag to `jenkins-agent` binary (regression in 3.25-3)
  Dockerfile
  Dockerfile-alpine
  Dockerfile-jdk11
Labels: bug

#113 Add a License file to the repository
  LICENSE
Labels: documentation
