Repository jenkinsci/docker-inbound-agent, pull requests merged in 2019-12, with the labels that each got.

#131 Create CODEOWNERS
  .github/CODEOWNERS
Labels: chore

#134 Fix the Gitter chat link in the documentation
  README.md
Labels: bug

#135 #133 - Update Remoting to 3.36 with `-help` and `-version` commands
  Dockerfile
  Dockerfile-alpine
  Dockerfile-jdk11
Labels: enhancement

#122 Fix version labels in Dockerfiles
  Dockerfile
  Dockerfile-alpine
  Dockerfile-jdk11
  Dockerfile-windows
Labels: bug
