Repository jenkinsci/docker-inbound-agent, pull requests merged in 2020-04, with the labels that each got.

#154 Rework directory structure and Windows containers + Update Windows parent image versions
  .gitignore
  11/debian/Dockerfile
  11/nanoserver-1809/Dockerfile
  11/windowsservercore-1809/Dockerfile
  8/alpine/Dockerfile
  8/debian/Dockerfile
  8/nanoserver-1809/Dockerfile
  8/windowsservercore-1809/Dockerfile
  Jenkinsfile
  Makefile
  README.md
  jenkins-agent.ps1
  make.ps1
  tests/jnlpAgent.Tests.ps1
  tests/netcat-helper/Dockerfile-windows
  tests/test_helpers.bash
  tests/test_helpers.psm1
  tests/tests.bats
Labels: chore, dependencies

#158 INFRA-1105 - Rename the image to jenkins/inbound-agent
  README.md
Labels: enhancement

#161 Cleanup Docker badges in README
  README.md
Labels: documentation

#159 [INFRA-1105] - Update the base image to jenkins/agent:4.3-4, cleanup old metadata
  11/debian/Dockerfile
  11/nanoserver-1809/Dockerfile
  11/windowsservercore-1809/Dockerfile
  8/alpine/Dockerfile
  8/debian/Dockerfile
  8/nanoserver-1809/Dockerfile
  8/windowsservercore-1809/Dockerfile
  tests/jnlpAgent.Tests.ps1
  tests/tests.bats
Labels: dependencies

#160 Rename Windows images so that a standard DockerHub repo is used
  README.md
  make.ps1
Labels: chore

#164 Show GitHub stars and repo quick link on the DockerHub landing page
  README.md
Labels: documentation

#166 Fix the jenkins/inbound-agent DockerHub link in README
  README.md
Labels: documentation

#163 Add dependabot config
  .dependabot/config.yml
Labels: chore

#167 Fix Windows image publishing for tagged releases
  Jenkinsfile
Labels: chore
