Repository jenkinsci/docker-inbound-agent, pull requests merged in 2022-01, with the labels that each got.

#253 Build agent newer agent image
  docker-bake.hcl
Labels: chore

#252 Add Java 17 alpine
  17/alpine/Dockerfile
  17/debian/Dockerfile
  docker-bake.hcl
  jenkins-agent
Labels: enhancement

#254 Allow the use of multiple arguments
  jenkins-agent
Labels: enhancement

#257 Revert "Allow the use of multiple arguments"
  jenkins-agent
Labels: bug
