Repository jenkinsci/docker-inbound-agent, pull requests merged in 2022-09, with the labels that each got.

#275 Remove -preview from jdk17 images
  17/debian/Dockerfile
  docker-bake.hcl
Labels: chore

#277 Stop publishing jdk 8 remoting on master branch
  docker-bake.hcl
Labels: bug

#281 Update base image to latest remoting
  docker-bake.hcl
  make.ps1
Labels: enhancement, chore

#284 chore(Release Drafter) cleanup and allow manual execution
  .github/release-drafter.yml
  .github/workflows/changelog.yml
  .github/workflows/release-drafter.yml
Labels: chore

#287 hotfix(windows) fix deploy error on the pipeline
  Jenkinsfile
Labels: bug

#286 chore(test) fix build argument tests by using an old version
  tests/inboundAgent.Tests.ps1
  tests/tests.bats
Labels: chore

#288 hotfix(windows) correct pipeline error when deploying
  Jenkinsfile
Labels: bug
