Repository jenkinsci/docker-inbound-agent, pull requests merged in 2023-04, with the labels that each got.

#344 chore(windows tests) improve harness (`docker` flags and commands)
  tests/inboundAgent.Tests.ps1
Labels: chore

#343 cleanup(windows) remove custom user (feature parity with Linux and delegating to parent image)
  11/windows/nanoserver-1809/Dockerfile
  11/windows/windowsservercore-ltsc2019/Dockerfile
  17/windows/nanoserver-1809/Dockerfile
  17/windows/windowsservercore-ltsc2019/Dockerfile
  tests/inboundAgent.Tests.ps1
Labels: cleanup

#339 Adding ppc64le builds for docker-inbound-agent
  Makefile
  docker-bake.hcl
  updatecli/updatecli.d/jenkins-agent-parent.yaml
Labels: enhancement
