Repository jenkinsci/docker-inbound-agent, pull requests merged in 2023-07, with the labels that each got.

#367 chore: remove outdated TODO comment from Alpine Dockerfile
  alpine/Dockerfile
Labels: skip-changelog

#363 refactor: build `docker-inbound-agent` like `docker-agent`
  Jenkinsfile
  build-windows.yaml
  build.ps1
  docker-bake.hcl
  make.ps1
  tests/inboundAgent.Tests.ps1
  tests/netcat-helper/Dockerfile-windows
  tests/test_helpers.psm1
  tests/tests.bats
  updatecli/updatecli.d/docker-agent.yaml
  windows/nanoserver/Dockerfile
  windows/windowsservercore/Dockerfile
Labels: chore

#370 chore(updatecli): correct target in docker-agent.yaml
  updatecli/updatecli.d/docker-agent.yaml
Labels: chore

#371 feat: add Windows 2022 docker inbound agent images
  Jenkinsfile
Labels: enhancement

#377 chore(updatecli): fix `docker-agent` manifest
  updatecli/updatecli.d/docker-agent.yaml
Labels: skip-changelog

#374 fixup: correct tags and publication for Windows images
  build-windows.yaml
  build.ps1
Labels: skip-changelog

#381 chore: fix link in README
  README.md
Labels: skip-changelog

#380 chore: trim spaces in build.ps1
  build.ps1
Labels: skip-changelog

#382 fixup(Jenkinsfile) use simple quotes for `powershell` steps
  Jenkinsfile
Labels: skip-changelog
