Repository jenkinsci/docker-inbound-agent, pull requests merged in 2023-10, with the labels that each got.

#420 chore: remove dead code in Makefile
  Makefile
Labels: chore, skip-changelog, cleanup

#417 documentation(README): add description for secret
  README.md
  images/screen-1.png
  images/screen-2.png
  images/screen-3.png
  images/screen-4.png
  images/screen-5.png
  images/screen-6.png
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#422 feat: bump parent agent to `3148.v532a_7e715ee3-11`
  alpine/Dockerfile
  build.ps1
  debian/Dockerfile
  docker-bake.hcl
  windows/nanoserver/Dockerfile
  windows/windowsservercore/Dockerfile
Labels: dependencies, feature

#418 feat(Windows): add Java 21 and bump `jenkins/agent` parent images to `3148.v532a_7e715ee3-12`
  alpine/Dockerfile
  build-windows.yaml
  build.ps1
  debian/Dockerfile
  docker-bake.hcl
  tests/inboundAgent.Tests.ps1
  updatecli/updatecli.d/docker-agent.yaml
  windows/nanoserver/Dockerfile
  windows/windowsservercore/Dockerfile
Labels: enhancement, windows, jdk21

#419 breaking: set Java 17 as default
  Makefile
  build.ps1
  docker-bake.hcl
  tests/inboundAgent.Tests.ps1
Labels: enhancement, breaking, jdk17

#428 Remove usage of deprecated `-headless` argument
  jenkins-agent
  jenkins-agent.ps1
Labels: chore

#368 chore(updatecli): track `nmap` version (used in Windows tests)
  updatecli/updatecli.d/nmap.yaml
Labels: chore, skip-changelog, dependencies, tests, updatecli

#433 Bump the parent image `jenkins/agent` version to 3174.v2c9e67f8f9df-1
  alpine/Dockerfile
  build.ps1
  debian/Dockerfile
  docker-bake.hcl
  windows/nanoserver/Dockerfile
  windows/windowsservercore/Dockerfile
Labels: dependencies

#432 Bump the parent image `jenkins/agent` version to 3176.v207ec082a_8c0-1
  alpine/Dockerfile
  build.ps1
  debian/Dockerfile
  docker-bake.hcl
  windows/nanoserver/Dockerfile
  windows/windowsservercore/Dockerfile
Labels: dependencies

#434 Upgrade JDK 21 images to latest Remoting
  alpine/Dockerfile-jdk21
  debian/Dockerfile-jdk21
Labels: bug, jdk21, alpine, debian

#435 chore(updatecli) fix docker-agent manifest to track missing files
  updatecli/updatecli.d/docker-agent.yaml
Labels: chore, updatecli, jdk21, alpine, debian

#437 fix(updatecli): check preview parent images only for some architectures
  updatecli/updatecli.d/docker-agent.yaml
Labels: chore, updatecli, jdk21, jdk21-preview

#439 fixup(updatecli): add `-preview` suffix to parent image version in jdk21-preview Dockerfiles
  updatecli/updatecli.d/docker-agent.yaml
Labels: chore, skip-changelog, updatecli, jdk21-preview

#436 feat(Linux): switch supported architectures to GA Temurin jdk21 images
  alpine/Dockerfile
  alpine/Dockerfile-jdk21
  build.ps1
  debian/Dockerfile
  debian/preview/Dockerfile
  docker-bake.hcl
  tests/tests.bats
  updatecli/updatecli.d/docker-agent.yaml
  windows/nanoserver/Dockerfile
  windows/windowsservercore/Dockerfile
Labels: enhancement, jdk21, alpine, debian, jdk21-preview

#443 fix: actually build and publish `debian_jdk21_preview` image
  docker-bake.hcl
Labels: bug, debian, jdk21-preview

#445 Migrate to new Remoting calling convention
  jenkins-agent
  jenkins-agent.ps1
Labels: chore
